
STARS_CHECKED = "2026-07-31"

RUNTIMES = (
    {
        "name": "transformers",
        "engine": "transformers-stt / transformers-tts",
        "kind": "STT + TTS",
        "github": "https://github.com/huggingface/transformers",
        "stars": 163_179,
        "installs": 178_306_500,
        "status": "optional",
        "extra": "transformers",
        "windows": True,
        "accelerators": ("CPU", "CUDA", "Apple MPS"),
        "summary": "29 speech-to-text and 11 text-to-speech architectures, including "
                   "upstream Whisper, wav2vec2 and the 1000-language MMS family.",
    },
    {
        "name": "OpenAI Whisper",
        "engine": "mlx-whisper / faster-whisper / whisper-cpp",
        "kind": "STT model family",
        "github": "https://github.com/openai/whisper",
        "stars": 106_194,
        "installs": 4_006_967,
        "status": "built-in",
        "extra": None,
        "windows": True,
        "accelerators": ("CPU", "CUDA", "Apple MLX"),
        "summary": "The family behind ses's multilingual choices, run through three "
                   "faster reimplementations rather than the original.",
    },
    {
        "name": "whisper.cpp",
        "engine": "whisper-cpp",
        "kind": "STT",
        "github": "https://github.com/ggml-org/whisper.cpp",
        "stars": 52_447,
        "installs": 214_296,
        "status": "optional",
        "extra": "whisper-cpp",
        "windows": True,
        "accelerators": ("CPU", "CUDA", "Vulkan", "OpenVINO"),
        "summary": "GGML-quantized Whisper, the smallest downloads in the library.",
    },
    {
        "name": "Chatterbox",
        "engine": "chatterbox",
        "kind": "TTS",
        "github": "https://github.com/resemble-ai/chatterbox",
        "stars": 25_785,
        "installs": 197_008,
        "status": "optional",
        "extra": "chatterbox",
        "windows": True,
        "accelerators": ("CPU", "CUDA", "Apple MPS"),
        "summary": "Voice cloning from a short sample; 23 languages including Turkish.",
    },
    {
        "name": "faster-whisper",
        "engine": "faster-whisper",
        "kind": "STT",
        "github": "https://github.com/SYSTRAN/faster-whisper",
        "stars": 24_641,
        "installs": 8_456_621,
        "status": "built-in",
        "extra": None,
        "windows": True,
        "accelerators": ("CPU", "CUDA"),
        "summary": "The most installed speech runtime there is, and how ses reaches "
                   "Windows and Linux.",
    },
    {
        "name": "WhisperX",
        "engine": None,
        "kind": "STT + diarization",
        "github": "https://github.com/m-bain/whisperX",
        "stars": 23_346,
        "installs": 1_380_644,
        "status": "missing",
        "extra": None,
        "windows": True,
        "accelerators": ("CPU", "CUDA"),
        "summary": "Word-level timestamps and speaker diarization. ses has no answer "
                   "for who spoke when.",
    },
    {
        "name": "FunASR",
        "engine": None,
        "kind": "STT",
        "github": "https://github.com/modelscope/FunASR",
        "stars": 19_563,
        "installs": 464_225,
        "status": "missing",
        "extra": None,
        "windows": True,
        "accelerators": ("CPU", "CUDA"),
        "summary": "Alibaba's SenseVoice and Paraformer, strongest on Chinese.",
    },
    {
        "name": "NVIDIA NeMo",
        "engine": None,
        "kind": "STT toolkit",
        "github": "https://github.com/NVIDIA/NeMo",
        "stars": 17_837,
        "installs": 1_456_368,
        "status": "external",
        "extra": None,
        "windows": True,
        "accelerators": ("CPU", "CUDA"),
        "summary": "Where Parakeet and Canary come from. ses runs their ONNX ports "
                   "instead of the training toolkit.",
    },
    {
        "name": "Vosk",
        "engine": "vosk",
        "kind": "STT",
        "github": "https://github.com/alphacep/vosk-api",
        "stars": 15_012,
        "installs": 640_809,
        "status": "optional",
        "extra": "vosk",
        "windows": True,
        "accelerators": ("CPU",),
        "summary": "Per-language models around 40 MB, so the language can never drift.",
    },
    {
        "name": "sherpa-onnx",
        "engine": None,
        "kind": "STT + TTS + VAD",
        "github": "https://github.com/k2-fsa/sherpa-onnx",
        "stars": 13_880,
        "installs": 531_510,
        "status": "missing",
        "extra": None,
        "windows": True,
        "accelerators": ("CPU", "CUDA", "CoreML"),
        "summary": "Embedded-focused ONNX runtime; overlaps what onnx-asr already gives ses.",
    },
    {
        "name": "SpeechBrain",
        "engine": None,
        "kind": "research toolkit",
        "github": "https://github.com/speechbrain/speechbrain",
        "stars": 11_726,
        "installs": 1_675_345,
        "status": "missing",
        "extra": None,
        "windows": True,
        "accelerators": ("CPU", "CUDA"),
        "summary": "Broad research toolkit, heavier than ses's one-command promise.",
    },
    {
        "name": "silero-vad",
        "engine": "built into live capture",
        "kind": "voice activity detection",
        "github": "https://github.com/snakers4/silero-vad",
        "stars": 9_804,
        "installs": 1_214_241,
        "status": "optional",
        "extra": "vad",
        "windows": True,
        "accelerators": ("CPU",),
        "summary": "Learned speech detection for live transcription. Steadier than the "
                   "built-in energy threshold once a room gets noisy.",
    },
    {
        "name": "mlx-whisper",
        "engine": "mlx-whisper",
        "kind": "STT",
        "github": "https://github.com/ml-explore/mlx-examples",
        "stars": 8_858,
        "installs": 315_028,
        "status": "built-in",
        "extra": None,
        "windows": False,
        "accelerators": ("Apple MLX",),
        "summary": "Whisper on the Apple GPU.",
    },
    {
        "name": "Kokoro",
        "engine": "kokoro-onnx",
        "kind": "TTS",
        "github": "https://github.com/hexgrad/kokoro",
        "stars": 8_192,
        "installs": 523_413,
        "status": "built-in",
        "extra": None,
        "windows": True,
        "accelerators": ("CPU", "CoreML"),
        "summary": "The most downloaded open voice model, 54 voices, 8 languages.",
    },
    {
        "name": "mlx-audio",
        "engine": "mlx-audio / mlx-audio-stt",
        "kind": "STT + TTS",
        "github": "https://github.com/Blaizzy/mlx-audio",
        "stars": 7_654,
        "installs": 362_747,
        "status": "optional",
        "extra": "mlx-audio",
        "windows": False,
        "accelerators": ("Apple MLX",),
        "summary": "38 speech families on the Apple GPU, including Qwen3-ASR and Nemotron.",
    },
    {
        "name": "Piper",
        "engine": "piper",
        "kind": "TTS",
        "github": "https://github.com/OHF-Voice/piper1-gpl",
        "stars": 4_959,
        "installs": 845_996,
        "status": "built-in",
        "extra": None,
        "windows": True,
        "accelerators": ("CPU",),
        "summary": "49 languages at roughly 20x real time, the fastest speech in ses.",
    },
    {
        "name": "onnx-asr",
        "engine": "onnx-asr",
        "kind": "STT",
        "github": "https://github.com/istupakov/onnx-asr",
        "stars": 354,
        "installs": 234_048,
        "status": "optional",
        "extra": "onnx-asr",
        "windows": True,
        "accelerators": ("CPU", "CUDA"),
        "summary": "Parakeet and Canary on every platform, with onnxruntime as its "
                   "only real weight.",
    },
)


def entries():
    entries = []
    for runtime in RUNTIMES:
        row = dict(runtime, stars_checked=STARS_CHECKED)
        row["description"] = row["summary"]
        row["accelerator"] = ", ".join(row["accelerators"])
        entries.append(row)
    return entries
